version: '3.4'
services:
  api:
    build: ./src
    restart: always
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload

    volumes:
      - ./src:/app

    ports:
      - 8000:8000
    depends_on:
      - mongo_library

  mongo_library:
    image: mongo:latest

    environment:
      - MONGO_INITDB_ROOT_USERNAM=admin
      - MONGODB_INITDB_ROOT_PASSWORD=16551655

    ports:
      - 27017:27017